NavBar Links shown appropriately based off logged in status.
slashroots/harvest-v2 pull request #113
Opened 2016-11-28 20:54 UTC by thinkking

The navbar links will now only reveal 'Dashboard' for a logged in user. This fixes #96 and fixes #50

2016-11-29 18:03 UTC, matjames007 commented on views/docs.ejs
@thinkking is this file being used? -if not remove it

2016-11-29 18:03 UTC, matjames007 commented on public/javascript/controllers/user-ctrl.js
> +            $scope.isActive = function (linkPath) {
@thinkking What does this do?  Comment the code.

2016-11-29 18:03 UTC, matjames007 commented on public/javascript/controllers/user-ctrl.js
> +
@thinkking writing jQuery within angular framework is bad.  Attempt to rewrite this controller using Angular functions.

2016-11-29 18:03 UTC, matjames007 commented on models/db.js
> +mongoose.connect(process.env.MONGOLAB_URI || "localhost:27017/mongodb");
@thinkking change this.

2016-11-29 18:04 UTC, matjames007 requested changes
Comments made within the in-line commenting feature.  Please review.

2016-11-29 18:35 UTC, thinkking commented on views/docs.ejs
Yes, it is. The original `/docs` path to the documentation is still available but is now being used to load the docs as an iframe as described in the pull request (#133) description. This had to be done to facilitate the docs' tab being shown as active as angular will not detect a path outside the app.

2016-11-29 19:43 UTC, thinkking commented
@matjames007 this pull request may be reviewed again.

2016-11-29 20:30 UTC, matjames007 commented
@thinkking merge in `develop`.

Issues:

- iFrame is a bad way for presenting the documentation and presents additional issues when the page is scaled to a tablet display
- Instead of making one call to load the page, two calls are made to the server with twice the calls for all the page resources used by the application.  This means that an instance of the angular application is running with an instance of the docs.ejs page inside the iframe with almost all the same scripts, styling files and html elements.
- Please ensure that you cover all the changes you did in the commit messages.

This being said - i suggest you demonstrate the functionality to another core team member for feedback on whether this can be merge in as part of the MVP.

2016-11-30 21:56 UTC, matjames007 commented
Not sure what happened with those commits @thinkking .... but I think the .yaml file is broken and doesn't render well in redoc.

2016-12-01 18:55 UTC, thinkking commented
@matjames007 and @nick22891 this pull request may be reviewed again. The docs are showing as they should due to a few lines of styling I had to do to the `main.css` we have for our docs.

2016-12-01 18:56 UTC, matjames007 commented on models/db.js
> +mongoose.connect(process.env.MONGOLAB_URI ||  "localhost:27017/mongodb");
@thinkking change again....

2016-12-01 18:58 UTC, thinkking commented
@matjames007 the mongoose.connect() arguments have been reverted.

2016-12-01 19:04 UTC, matjames007 approved these changes

2016-12-01 19:04 UTC, merged