Email RADA on User Signup
slashroots/harvest-v2 pull request #194
Opened 2017-05-11 21:47 UTC by nick22891

This branch implements a notification email to RADA when a new user signs up to use the API. It's sent to harvestapi@rada.gov.jm and it writes a log to indicate success or failure - similar to what was done for the email that we send to the users themselves.

2017-05-11 22:26 UTC, matjames007 requested changes
Remove the hardcoded item from the code.

2017-05-11 22:26 UTC, matjames007 commented on routes/user/user.js
> +            common.sendEmail("harvestapi@rada.gov.jm", "New HarvestAPI User", "A new user with email address " + user.us_email_address + " has signed up to use the API.", function (error, info) {
The `harvestapi@rada.gov.jm` email address should be configurable as an environment variable - not hardcoded.

2017-05-12 12:44 UTC, nick22891 commented
@matjames007 This can be reviewed again.

2017-05-12 15:30 UTC, matjames007 approved these changes

2017-05-12 15:31 UTC, merged