Implementation of the Developer Dashboard
slashroots/harvest-v2 pull request #34
Opened 2016-10-23 21:06 UTC by nick22891

This pull request implements the functionality in the new design for the developer dashboard including : searching for applications, enabling and disabling applications (including - as per @matjames007 's recommendations - a rewrite of the way this was previously implemented), small visual effects like the hover effect on each application that shows the caret drop down from which the buttons for enabling and disabling an application may be selected.

In short, this pull request covers the developer dashboard with the exception of the navigation bar which will follow shortly in a separate pull request.

2016-10-23 21:15 UTC, nick22891 commented
Decided to just make the few navigation bar edits here after all since all the requisite new CSS is on this branch already.

2016-10-31 21:26 UTC, matjames007 commented on public/partials/dashboard.html
> +                <div style="display: table-cell;" ng-repeat="app in apps | filter:searchText" class="col-md-6 app-wrap" ng-class="!isEven($index) ? 'col-md-offset-1' : 'dummy'">
@nick22891 css has it's own stuff to achieve the functionality you want.  Try using pure css to do this.

2016-10-31 21:27 UTC, matjames007 commented on public/javascript/controllers/user-ctrl.js
> +                console.log("Nick");
remove @nick22891

2016-10-31 21:30 UTC, matjames007 commented on public/javascript/controllers/user-ctrl.js
> +        function($scope, $location, $routeParams, $filter, CurrentUserFactory, UserAppsFactory, AppFactory, AppDisableFactory, PlatformFactory) {
What is expected to be passed in as `$routeParams`?

2016-10-31 21:34 UTC, matjames007 commented on public/partials/common/navigation.html
> -                    <a href="">ABIS Home Page <i class="fa fa-external-link fa-fw"></i></a>
@CamiMonte and @nick22891 wasn't there a requirement for us to be able to link back to the RADA home page from the application?

2016-10-31 21:37 UTC, matjames007 commented on public/partials/dashboard.html
> +            <div class="col-md-12" style="display: table;">
@CamiMonte and @nick22891 remember to move inline css to the actual style.css file that is imported at runtime.

2016-10-31 21:41 UTC, matjames007 commented on routes/app/app-manager.js
> +exports.modifyApp = function(req, res, next) {
@nick22891 is the state the only thing that you will be modifying in an app?  Suppose I want to modify the name or description of the application?

2016-10-31 21:43 UTC, matjames007 commented on routes/user/user.js
> +        App.findOne({ ap_app_token: token, ap_app_status: "active" })
good thinking... i missed this case.

2016-10-31 21:44 UTC, matjames007 requested changes
Review the comments left within the code changes.

2016-11-07 13:19 UTC, matjames007 commented on routes/app/app-manager.js
> +exports.modifyApp = function(req, res, next) {
@nick22891 think you might have missed this one.  Is the app state the only parameter to be changed?

2016-11-07 13:20 UTC, matjames007 commented on public/javascript/services.js
> +services.factory('AppDisableFactory', function($resource) {
@nick this can do more than just disable can't it?  This route can modify the entire application parameters.

2016-11-13 22:48 UTC, matjames007 approved these changes

2016-11-13 22:49 UTC, merged